[package]
name = "email"
version = "0.1.0"
edition = "2024"

[dependencies]
tera = "1.20.0"

[dependencies.lettre]
version = "0.11.15"
default-features = false
features = ["tokio1", "tokio1-rustls-tls", "smtp-transport", "builder", "serde"]
