FROM rust:latest AS builder

# Set the working directory inside the container
WORKDIR /usr/src/app

# Copy the Cargo.toml and Cargo.lock files
COPY ./ ./

# build
RUN cargo build --release

FROM debian:stable-slim

# Set the working directory inside the container
WORKDIR /usr/src/app

COPY --from=builder /usr/src/app/target/release/blossom_backend_rs ./
COPY --from=builder /usr/src/app/.env ./

CMD ["./blossom_backend_rs"]