services:
  postgres:
    image: postgres:latest
    container_name: blossom_postgres
    env_file: .env
    environment:
      POSTGRES_PASSWORD: ${DATABASE_ROOT_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
      - ./init/pgsql:/docker-entrypoint-initdb.d
    networks:
      - app-network
    ports:
      - "5432:5432"
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U postgres -d postgres" ]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    env_file: .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ROOT_USER}
      MINIO_ROOT_PASSWORD: ${MINIO_ROOT_PASSWORD}
    command: server /data --console-address ":9090" --address ":9000"
    volumes:
      - minio_data:/data
      - ./init/minio:/docker-entrypoint-initdb.d
    networks:
      - app-network
    ports:
      - "9000:9000"
      - "9090:9090"
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 2s
      retries: 5

  backend:
    build: .
    container_name: blossom_backend_rs
    env_file: .env
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    ports:
      - "8000:8000"
    networks:
      - app-network
    volumes:
      - cargo_registry:/root/.cargo/registry


volumes:
  postgres_data:
  minio_data:
  cargo_registry:

networks:
  app-network:
    driver: bridge