services:
  postgres:
    image: postgres:latest
    container_name: blossom_postgres
    env_file: .env
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - app-network
    healthcheck:
      test: [ "CMD-SHELL", "pg_isready -U ${DATABASE_USER} -d ${DATABASE_NAME}" ]
      interval: 5s
      timeout: 5s
      retries: 5

  minio:
    image: minio/minio
    env_file: .env
    environment:
      MINIO_ROOT_USER: ${MINIO_ACCESS_KEY}
      MINIO_ROOT_PASSWORD: ${MINIO_SECRET_KEY}
    command: server /data --console-address ":9090" --address ":9000"
    volumes:
      - minio_data:/data
    networks:
      - app-network
    ports:
      - "9000:9000"
      - "9090:9090"
    healthcheck:
      test: [ "CMD", "mc", "ready", "local" ]
      interval: 5s
      timeout: 2s
      retries: 5

  backend:
    build: .
    container_name: blossom_backend_rs
    depends_on:
      postgres:
        condition: service_healthy
      minio:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - cargo_registry:/root/.cargo/registry


volumes:
  postgres_data:
  minio_data:
  cargo_registry:

networks:
  app-network:
    driver: bridge