[default]
address = "127.0.0.1"
port = 8000

[default.limits]
form = "64 kB"
json = "1 MiB"
msgpack = "2 MiB"
"file/jpg" = "5 MiB"

[debug]
secret_key = "53TT+QbanKHTV4YWS/XL5j33E85IovODt6rzdl50gCQ="

[release]
secret_key = "LEulMJea4JGn8pzh2maHAihBt/oXDzFXwYSn/wMwhy8="
address = "0.0.0.0"
port = 8000