[package]
name = "utils"
version = "0.1.0"
edition = "2024"

[dependencies]
rocket = { version = "0.5.1", features = ["secrets", "tls", "json", "uuid"] }
partial_form_codegen = { path = "./partial_form_codegen" }