#!/bin/bash
set -e

psql -U postgres <<EOF
DO \$$
  BEGIN
    IF NOT EXISTS (SELECT FROM pg_roles WHERE rolname = '${APP_DB_USER}') THEN
      CREATE ROLE ${APP_DB_USER} SUPERUSER PASSWORD '${APP_DB_PASSWORD}' LOGIN;
    END IF;
  END
\$$;
EOF

psql -U postgres <<EOF
SELECT 'CREATE DATABASE ${APP_DB_NAME}'
WHERE NOT EXISTS (SELECT FROM pg_database WHERE datname = '${APP_DB_NAME}')\gexec
EOF

psql -U postgres -d "${APP_DB_NAME}" <<EOF
GRANT ALL PRIVILEGES ON DATABASE ${APP_DB_NAME} TO ${APP_DB_USER};
GRANT CONNECT ON DATABASE ${APP_DB_NAME} TO ${APP_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON TABLES TO ${APP_DB_USER};
ALTER DEFAULT PRIVILEGES IN SCHEMA public GRANT ALL ON SEQUENCES TO ${APP_DB_USER};
EOF